#This script was run in /scratch/halstead/c/ccrane/raksha, where the data files resided.
library("qtl2")
namR<- read_cross2("NAMtarspotRqtl.yaml")
mapR <- insert_pseudomarkers(namR$gmap, step=1)
probsR <- calc_genoprob(namR, mapR, error_prob=0.002)
pheno <- namR$pheno
outR <- scan1(probsR, pheno)
svg("NAMtarspotRqtlbasica.svg", height = 5, width = 10)
ylimR <- c(0, maxlod(outR)*1.02)
plot_scan1(outR, mapR, lodcolumn=1, col = "black")
capture.output(find_peaks(outR, mapR, threshold=1.6, peakdrop=1.5, drop=1.5), file = "NAMtarspotpeaksR.txt")
capture.output(bayes_int(outR, mapR, lodcolumn=1, chr=7, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksR.txt", append = TRUE)
capture.output(bayes_int(outR, mapR, lodcolumn=1, chr=8, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksR.txt", append = TRUE)
capture.output(bayes_int(outR, mapR, lodcolumn=1, chr=9, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksR.txt", append = TRUE)
permR <- scan1perm(probsR, pheno, n_perm=5000)
capture.output(summary(permR, alpha=c(0.01, 0.05, 0.10, 0.20)), file = "NAMtarspotpermsR.txt")
dev.off()
kinshipR <- calc_kinship(probsR, "loco")
out_lmmR <- scan1(probsR, pheno, kinshipR)
svg("NAMtarspotRqtllmma.svg", height = 5, width = 10)
plot_scan1(out_lmmR, mapR, lodcolumn=1, col = "black")
capture.output(find_peaks(out_lmmR, mapR, threshold=1.6, peakdrop=1.5, drop=1.5), file = "NAMtarspotpeakslmmR.txt")
capture.output(bayes_int(out_lmmR, mapR, lodcolumn=1, chr=2, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmR.txt", append = TRUE)
capture.output(bayes_int(out_lmmR, mapR, lodcolumn=1, chr=5, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmR.txt", append = TRUE)
capture.output(bayes_int(out_lmmR, mapR, lodcolumn=1, chr=8, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmR.txt", append = TRUE)
capture.output(bayes_int(out_lmmR, mapR, lodcolumn=1, chr=9, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmR.txt", append = TRUE)
permlmmR <- scan1perm(probsR, pheno, kinshipR, n_perm=5000)
capture.output(summary(permlmmR, alpha=c(0.01, 0.05, 0.10, 0.20)), file = "NAMtarspotpermslmmR.txt")
dev.off()
namr<- read_cross2("NAMtarspotrqtl.yaml")
mapr <- insert_pseudomarkers(namr$gmap, step=1)
probsr <- calc_genoprob(namr, mapr, error_prob=0.002)
pheno <- namr$pheno
outr <- scan1(probsr, pheno)
svg("NAMtarspotrqtlbasicb.svg", height = 5, width = 10)
ylimr <- c(0, maxlod(outr)*1.02)
plot_scan1(outr, mapr, lodcolumn=1, col = "black")
capture.output(find_peaks(outr, mapr, threshold=1.6, peakdrop=1.5, drop=1.5), file = "NAMtarspotpeaksr.txt")
capture.output(bayes_int(outr, mapr, lodcolumn=1, chr=3, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksr.txt", append = TRUE)
capture.output(bayes_int(outr, mapr, lodcolumn=1, chr=7, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksr.txt", append = TRUE)
capture.output(bayes_int(outr, mapr, lodcolumn=1, chr=8, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksr.txt", append = TRUE)
capture.output(bayes_int(outr, mapr, lodcolumn=1, chr=9, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksr.txt", append = TRUE)
permr <- scan1perm(probsr, pheno, n_perm=5000)
capture.output(summary(permr, alpha=c(0.01, 0.05, 0.10, 0.20)), file = "NAMtarspotpermsr.txt")
dev.off()
kinshipr <- calc_kinship(probsr, "loco")
out_lmmr <- scan1(probsr, pheno, kinshipr)
svg("NAMtarspotrqtllmmb.svg", height = 5, width = 10)
plot_scan1(out_lmmr, mapr, lodcolumn=1, col = "black")
capture.output(find_peaks(out_lmmr, mapr, threshold=1.6, peakdrop=1.5, drop=1.5), file = "NAMtarspotpeakslmmr.txt")
capture.output(bayes_int(out_lmmr, mapr, lodcolumn=1, chr=2, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmr.txt", append = TRUE)
capture.output(bayes_int(out_lmmr, mapr, lodcolumn=1, chr=5, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmr.txt", append = TRUE)
capture.output(bayes_int(out_lmmr, mapr, lodcolumn=1, chr=8, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmr.txt", append = TRUE)
capture.output(bayes_int(out_lmmr, mapr, lodcolumn=1, chr=9, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmr.txt", append = TRUE)
permlmmr <- scan1perm(probsr, pheno, kinshipr, n_perm=5000)
capture.output(summary(permlmmr, alpha=c(0.01, 0.05, 0.10, 0.20)), file = "NAMtarspotpermslmmr.txt")
dev.off()
