#This script was run in /scratch/halstead/c/ccrane/raksha, where the data files resided.
#For this script, we left out the permutation tests, which take about 10 minutes per lmm run.
library("qtl2")
namR<- read_cross2("NAMtarspotRqtl.yaml")
mapR <- insert_pseudomarkers(namR$gmap, step=1)
probsR <- calc_genoprob(namR, mapR, error_prob=0.002)
pheno <- namR$pheno
outR <- scan1(probsR, pheno)
svg("NAMtarspotRqtlbasica.svg", height = 5, width = 10)
ylimR <- c(0, maxlod(outR)*1.02)
plot_scan1(outR, mapR, lodcolumn=1, col = "black")
dev.off()
capture.output(find_peaks(outR, mapR, threshold=1.6, peakdrop=1.5, drop=1.5), file = "NAMtarspotpeaksR.txt")
capture.output(bayes_int(outR, mapR, lodcolumn=1, chr=7, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksR.txt", append = TRUE)
capture.output(bayes_int(outR, mapR, lodcolumn=1, chr=8, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksR.txt", append = TRUE)
capture.output(bayes_int(outR, mapR, lodcolumn=1, chr=9, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksR.txt", append = TRUE)
ceffR7 <- scan1coef(probsR[,"7"], pheno)
pdf("NAMtarspotqtleffectsRchr7.pdf", height = 5, width = 10)
plot_coef(ceffR7, mapR, columns=2, col = "black")
dev.off()
ceffR8 <- scan1coef(probsR[,"8"], pheno)
pdf("NAMtarspotqtleffectsRchr8.pdf", height = 5, width = 10)
plot_coef(ceffR8, mapR, columns=2, col = "black")
dev.off()
ceffR9 <- scan1coef(probsR[,"9"], pheno)
capture.output(ceffR9, file = "hh.txt")
pdf("NAMtarspotqtleffectsRchr9.pdf", height = 5, width = 10)
plot_coef(ceffR9, mapR, columns=2, col = "black")
dev.off()
#g <- maxmarg(pr, map, chr=2, pos=28.6, return_char=TRUE)
#permR <- scan1perm(probsR, pheno, n_perm=5000)
#capture.output(summary(permR, alpha=c(0.01, 0.05, 0.10, 0.20)), file = "NAMtarspotpermsR.txt")
kinshipR <- calc_kinship(probsR, "loco")
out_lmmR <- scan1(probsR, pheno, kinshipR)
svg("NAMtarspotRqtllmma.svg", height = 5, width = 10)
plot_scan1(out_lmmR, mapR, lodcolumn=1, col = "black")
capture.output(find_peaks(out_lmmR, mapR, threshold=1.6, peakdrop=1.5, drop=1.5), file = "NAMtarspotpeakslmmR.txt")
capture.output(bayes_int(out_lmmR, mapR, lodcolumn=1, chr=2, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmR.txt", append = TRUE)
capture.output(bayes_int(out_lmmR, mapR, lodcolumn=1, chr=5, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmR.txt", append = TRUE)
capture.output(bayes_int(out_lmmR, mapR, lodcolumn=1, chr=8, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmR.txt", append = TRUE)
capture.output(bayes_int(out_lmmR, mapR, lodcolumn=1, chr=9, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmR.txt", append = TRUE)
dev.off()
cefflmmR2 <- scan1coef(probsR[,"2"], pheno, kinshipR[["2"]])
pdf("NAMtarspotqtleffectslmmRchr2.pdf", height = 5, width = 10)
plot_coef(cefflmmR2, mapR, columns=2, col = "black")
dev.off()
cefflmmR5 <- scan1coef(probsR[,"5"], pheno, kinshipR[["5"]])
pdf("NAMtarspotqtleffectslmmRchr5.pdf", height = 5, width = 10)
plot_coef(cefflmmR5, mapR, columns=2, col = "black")
dev.off()
cefflmmR7 <- scan1coef(probsR[,"7"], pheno, kinshipR[["7"]])
pdf("NAMtarspotqtleffectslmmRchr7.pdf", height = 5, width = 10)
plot_coef(cefflmmR7, mapR, columns=2, col = "black")
dev.off()
cefflmmR8 <- scan1coef(probsR[,"8"], pheno, kinshipR[["8"]])
pdf("NAMtarspotqtleffectslmmRchr8.pdf", height = 5, width = 10)
plot_coef(cefflmmR8, mapR, columns=2, col = "black")
dev.off()
cefflmmR9 <- scan1coef(probsR[,"9"], pheno, kinshipR[["9"]])
pdf("NAMtarspotqtleffectslmmRchr9.pdf", height = 5, width = 10)
plot_coef(cefflmmR9, mapR, columns=2, col = "black")
dev.off()
#permlmmR <- scan1perm(probsR, pheno, kinshipR, n_perm=5000)
#capture.output(summary(permlmmR, alpha=c(0.01, 0.05, 0.10, 0.20)), file = "NAMtarspotpermslmmR.txt")
namr<- read_cross2("NAMtarspotrqtl.yaml")
mapr <- insert_pseudomarkers(namr$gmap, step=1)
probsr <- calc_genoprob(namr, mapr, error_prob=0.002)
pheno <- namr$pheno
outr <- scan1(probsr, pheno)
svg("NAMtarspotrqtlbasicb.svg", height = 5, width = 10)
ylimr <- c(0, maxlod(outr)*1.02)
plot_scan1(outr, mapr, lodcolumn=1, col = "black")
dev.off()
capture.output(find_peaks(outr, mapr, threshold=1.6, peakdrop=1.5, drop=1.5), file = "NAMtarspotpeaksr.txt")
capture.output(bayes_int(outr, mapr, lodcolumn=1, chr=3, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksr.txt", append = TRUE)
capture.output(bayes_int(outr, mapr, lodcolumn=1, chr=7, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksr.txt", append = TRUE)
capture.output(bayes_int(outr, mapr, lodcolumn=1, chr=8, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksr.txt", append = TRUE)
capture.output(bayes_int(outr, mapr, lodcolumn=1, chr=9, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeaksr.txt", append = TRUE)
ceffr7 <- scan1coef(probsr[,"7"], pheno)
pdf("NAMtarspotqtleffectsrchr7b.pdf", height = 5, width = 10)
plot_coef(ceffr7, mapr, columns=2, col = "black")
dev.off()
ceffr8 <- scan1coef(probsr[,"8"], pheno)
pdf("NAMtarspotqtleffectsrchr8b.pdf", height = 5, width = 10)
plot_coef(ceffr8, mapr, columns=2, col = "black")
dev.off()
ceffr9 <- scan1coef(probsr[,"9"], pheno)
pdf("NAMtarspotqtleffectsrchr9b.pdf", height = 5, width = 10)
plot_coef(ceffr9, mapr, columns=2, col = "black")
dev.off()
#permr <- scan1perm(probsr, pheno, n_perm=5000)
#capture.output(summary(permr, alpha=c(0.01, 0.05, 0.10, 0.20)), file = "NAMtarspotpermsr.txt")
kinshipr <- calc_kinship(probsr, "loco")
out_lmmr <- scan1(probsr, pheno, kinshipr)
svg("NAMtarspotrqtllmmb.svg", height = 5, width = 10)
plot_scan1(out_lmmr, mapr, lodcolumn=1, col = "black")
dev.off()
capture.output(find_peaks(out_lmmr, mapr, threshold=1.6, peakdrop=1.5, drop=1.5), file = "NAMtarspotpeakslmmr.txt")
capture.output(bayes_int(out_lmmr, mapr, lodcolumn=1, chr=2, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmr.txt", append = TRUE)
capture.output(bayes_int(out_lmmr, mapr, lodcolumn=1, chr=5, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmr.txt", append = TRUE)
capture.output(bayes_int(out_lmmr, mapr, lodcolumn=1, chr=8, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmr.txt", append = TRUE)
capture.output(bayes_int(out_lmmr, mapr, lodcolumn=1, chr=9, prob=0.95, peakdrop = 1.5), file = "NAMtarspotpeakslmmr.txt", append = TRUE)
cefflmmr1 <- scan1coef(probsr[,"1"], pheno, kinshipr[["1"]])
pdf("NAMtarspotqtleffectslmmrchr1b.pdf", height = 5, width = 10)
plot_coef(cefflmmr1, mapr, columns=2, col = "black")
dev.off()
cefflmmr2 <- scan1coef(probsr[,"2"], pheno, kinshipr[["2"]])
pdf("NAMtarspotqtleffectslmmrchr2b.pdf", height = 5, width = 10)
plot_coef(cefflmmr2, mapr, columns=2, col = "black")
dev.off()
cefflmmr5 <- scan1coef(probsr[,"5"], pheno, kinshipr[["5"]])
pdf("NAMtarspotqtleffectslmmrchr5b.pdf", height = 5, width = 10)
plot_coef(cefflmmr5, mapr, columns=2, col = "black")
dev.off()
cefflmmr7 <- scan1coef(probsr[,"7"], pheno, kinshipr[["7"]])
pdf("NAMtarspotqtleffectslmmrchr7b.pdf", height = 5, width = 10)
plot_coef(cefflmmr7, mapr, columns=2, col = "black")
dev.off()
cefflmmr8 <- scan1coef(probsr[,"8"], pheno, kinshipr[["8"]])
pdf("NAMtarspotqtleffectslmmrchr8b.pdf", height = 5, width = 10)
plot_coef(cefflmmr8, mapr, columns=2, col = "black")
dev.off()
cefflmmr9 <- scan1coef(probsr[,"9"], pheno, kinshipr[["9"]])
pdf("NAMtarspotqtleffectslmmrchr9b.pdf", height = 5, width = 10)
plot_coef(cefflmmr9, mapr, columns=2, col = "black")
dev.off()
#permlmmr <- scan1perm(probsr, pheno, kinshipr, n_perm=5000)
#capture.output(summary(permlmmr, alpha=c(0.01, 0.05, 0.10, 0.20)), file = "NAMtarspotpermslmmr.txt")
g1 <- maxmarg(probsr, mapr, chr=1, pos=73.60, return_char=TRUE)
g2 <- maxmarg(probsr, mapr, chr=1, pos=104.95, return_char=TRUE)
g3 <- maxmarg(probsr, mapr, chr=1, pos=107.32, return_char=TRUE)
g4 <- maxmarg(probsr, mapr, chr=1, pos=130.29, return_char=TRUE)
g5 <- maxmarg(probsr, mapr, chr=2, pos=53.30, return_char=TRUE)
g6 <- maxmarg(probsr, mapr, chr=2, pos=72.25, return_char=TRUE)
g7 <- maxmarg(probsr, mapr, chr=5, pos=0.66, return_char=TRUE)
g8 <- maxmarg(probsr, mapr, chr=5, pos=39.30, return_char=TRUE)
g9 <- maxmarg(probsr, mapr, chr=5, pos=63.62, return_char=TRUE)
g10 <- maxmarg(probsr, mapr, chr=7, pos=48.55, return_char=TRUE)
g11 <- maxmarg(probsr, mapr, chr=7, pos=71.90, return_char=TRUE)
g12 <- maxmarg(probsr, mapr, chr=8, pos=67.47, return_char=TRUE)
g13 <- maxmarg(probsr, mapr, chr=8, pos=68.60, return_char=TRUE)
g14 <- maxmarg(probsr, mapr, chr=8, pos=75.54, return_char=TRUE)
g15 <- maxmarg(probsr, mapr, chr=9, pos=26.09, return_char=TRUE)
g16 <- maxmarg(probsr, mapr, chr=9, pos=38.72, return_char=TRUE)
g17 <- maxmarg(probsr, mapr, chr=9, pos=39.59, return_char=TRUE)
pdf("NAMtarspotgenophenolmmrchr1_73.pdf", height = 4, width = 5)
plot_pxg(g1, pheno, xlab="Genotype at S1_47507876", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr1_105.pdf", height = 4, width = 5)
plot_pxg(g2, pheno, xlab="Genotype at S1_143776965", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr1_107.pdf", height = 4, width = 5)
plot_pxg(g3, pheno, xlab="Genotype at S1_158003964", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr1_130.pdf", height = 4, width = 5)
plot_pxg(g4, pheno, xlab="Genotype at S1_196430259", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr2_53.pdf", height = 4, width = 5)
plot_pxg(g5, pheno, xlab="Genotype at S2_32949539", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr2_72.pdf", height = 4, width = 5)
plot_pxg(g6, pheno, xlab="Genotype at S2_101542802", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr5_01.pdf", height = 4, width = 5)
plot_pxg(g7, pheno, xlab="Genotype at S5_904541", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr5_39.pdf", height = 4, width = 5)
plot_pxg(g8, pheno, xlab="Genotype at S5_16217226", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr5_64.pdf", height = 4, width = 5)
plot_pxg(g9, pheno, xlab="Genotype at S5_65092457", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr7_49.pdf", height = 4, width = 5)
plot_pxg(g10, pheno, xlab="Genotype at S7_98595833", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr7_72.pdf", height = 4, width = 5)
plot_pxg(g11, pheno, xlab="Genotype at S7_133374241", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr8_67.pdf", height = 4, width = 5)
plot_pxg(g12, pheno, xlab="Genotype at S8_118772166", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr8_69.pdf", height = 4, width = 5)
plot_pxg(g13, pheno, xlab="Genotype at S8_119256203", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr8_76.pdf", height = 4, width = 5)
plot_pxg(g14, pheno, xlab="Genotype at S8_131340845", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr9_26.pdf", height = 4, width = 5)
plot_pxg(g15, pheno, xlab="Genotype at S9_16322345", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr9_39.pdf", height = 4, width = 5)
plot_pxg(g16, pheno, xlab="Genotype at S9_43677789", ylab="Disease score")
dev.off()
pdf("NAMtarspotgenophenolmmrchr9_40.pdf", height = 4, width = 5)
plot_pxg(g17, pheno, xlab="Genotype at S9_57012908", ylab="Disease score")
dev.off()
